#!/usr/bin/make -f

default:
	@echo 'make linkedList'
	g++ --std=c++11 test_linked_list.cpp test_linked_list.h linkedList.cpp linkedList.h -o test_linked_list
clean:
	@echo 'make linkedList clean'
	@rm test_linked_list
